version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=backend
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge
